version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${RDS_PASSWORD}
      - POSTGRES_DB=${RDS_DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data


  api:
    image: python:3.8-slim
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./api:/app # This line mounts your local 'api' directory to '/app' in the container
    working_dir: /app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=${RDS_PASSWORD}
      - DB_NAME=${RDS_DB_NAME}
    ports:
      - "8000:8000" # Assuming FastAPI runs on port 8000 by default


volumes:
  postgres-db:
